### ISSUE TITLE
Shift key not handled correctly in events?

### ISSUE THREAD

**Issue by mhwombat** [jtdaugherty/vty-ui#56]
When a keypress handler is invoked, the parameters I would *expect* to be passed to it are:

key pressed  | Key parameter  | [Modifier] parameter
---------------- | -------------------- | -------------------------
z                   |  KASCII 'z'          | []
Shift+z          |  KASCII 'z'         | [MShift]
Ctrl+z           | KASCII 'z'           | [MCtrl]
Ctrl+Shift+z  | KASCII 'z'           | [MCtrl MShift]

But the parameters *actually* passed to it are:

key pressed  | Key parameter  | [Modifier] parameter | Note
---------------- | -------------------- | ------------------------- | ------ 
z                   |  KASCII 'z'          | []                              | GOOD
Shift+z          |  KASCII 'Z'         | []                               | OK, I guess
Ctrl+z           | KASCII 'z'           | [MCtrl]                       | GOOD
Ctrl+Shift+z  | KASCII 'z'           | [MCtrl]                       | Same as for Ctrl+z!

That is, Ctrl+Shift neither adds a shift modifier nor makes the character uppercase. I discovered this because I'm writing an editor, and I wanted to map Ctrl+z to "undo", and Ctrl+Shift+z to "redo". I have a little handler that prints information about a keypress to the status bar:

    dumpKey :: Widget FormattedText -> Widget a -> Key -> [Modifier] -> IO Bool
    dumpKey sb _ k ms = do
      setText sb . pack $ "Keypress: " ++ show ms ++ ' ':show k
      return False

So when I type `Ctrl+z`, it displays:

    Keypress: [MCtrl] KASCII 'z'

However, when I type `Ctrl+Shift+z`, it displays the exact same thing.

**Comment by jtdaugherty** [comment]
@coreyoconnor - do you have any insight as to what might be going on here?

**Comment by jtdaugherty** [comment]
(Granted, this is a somewhat stale issue and changes to `vty` might have fixed this by now.)

**Comment by coreyoconnor** [comment]
Terminator is a terminal emulator not a terminal program. This means that terminator has access to the hosts windowing system's events. This is not accessible by a terminal program. Terminator's shortcuts are handled at a layer above the terminal program.

Control-Shift-Z and Control-Z will be, by historical weirdness/ANSI standards, *always* the same for a terminal program. That comes from the day where keyboards were grids of wires and pressing a key actually just touched wires together. Shift, literally, pulled wire 7 to high. Control pulled wires 6 and 7 to ground. Hence: Shift is ignored when Control is pressed.

For instance, here is where Terminator implements the translation from windowing system key events to terminal input bytes:
* https://code.google.com/p/jessies/source/browse/terminator/trunk/src/terminator/view/JTerminalPane.java#492

Notice that both the capitalized letters and the lower case letters are shifted into the same range. That is consistent with all other terminal emulators.

For keys not in the ASCII range control, and control+shift can sometimes be differentiated. Again tho, that is subject to historical weirdness. EG: Terminfo only defines shift+right and shift+left, not shift+up or shift+down. ¯\_(ツ)_/¯

You know what we need? Another standard for terminals: https://xkcd.com/927/ ;-)

**Comment by jtdaugherty** [comment]
Thanks for the great explanation!
