### ISSUE TITLE
A general wrapper component

### ISSUE THREAD

**Issue by nikita-volkov** [jtdaugherty/vty-ui#57]
I suggest to add a component `Wrapper s w`, where `s` is some extra state added on top of the state of an existing component state `w`. All the rendering tasks should be forwarded to the wrapped component.

This will open the gates of composition and allow to write custom components made up of other components. 

E.g.,

```
type MyCustomComponent =
  Wrapper MyCustomState Table
```

All the API that `Wrapper` requires is the following:

```haskell
onState :: Widget (Wrapper s w) -> (s -> IO s) -> IO s
onWrappedWidget :: Widget (Wrapper s w) -> (Widget w -> IO a) -> a
```

The above functions will allow to control the extensional state and the wrapped widget.

---
I have tried implementing this myself only to find out that the current `Handlers` implementation makes it impossible to implement the functions `gainFocusHandlers`, `resizeHandlers` and `loseFocusHandlers` of `WidgetImpl` for the wrapper.

**Comment by jtdaugherty** [comment]
Okay. Since you've moved on, I'm going to close this for now. If you come back to using `vty-ui` then we can resume this discussion. Thanks!
