### ISSUE TITLE
release 1.9?

### ISSUE THREAD

**Issue by radix** [jtdaugherty/vty-ui#67]
I was able to build and test the `master` branch on GHC 7.10, but the release currently on cabal can't install. Is there anything else blocking a release of the latest code to cabal?

**Comment by jtdaugherty** [comment]
Nope, not that I know of; thanks for bringing this up. I should have time to do this in the next day or so, and I'll update here once the release is on Hackage.

**Comment by radix** [comment]
thanks @jtdaugherty!

**Comment by radix** [comment]
Actually, one error I did find: building the vty-ui-complex-demo failed with the following:

```
demos/ComplexDemo.hs:160:31:
    Couldn't match expected type ‘TimeLocale’
                with actual type ‘SL.TimeLocale’
    NB: ‘TimeLocale’
          is defined in ‘Data.Time.Format.Locale’ in package ‘time-1.5.0.1’
        ‘SL.TimeLocale’
          is defined in ‘System.Locale’ in package ‘old-locale-1.0.0.7’
    In the first argument of ‘formatTime’, namely
      ‘SL.defaultTimeLocale’
    In the second argument of ‘($)’, namely
      ‘formatTime SL.defaultTimeLocale SL.rfc822DateFormat t’
```

All the other demos build successfully and work.

**Comment by jtdaugherty** [comment]
Thanks!

**Comment by jtdaugherty** [comment]
(Closed due to bugfix commit, but 1.9 release is pending.)

**Comment by jtdaugherty** [comment]
Done: http://hackage.haskell.org/package/vty-ui-1.9

**Comment by radix** [comment]
:+1: it works :)
