### ISSUE TITLE
adding many rows to a list is very slow

### ISSUE THREAD

**Issue by radix** [jtdaugherty/vty-ui#68]
The app I'm writing wants to have a LOT of list items -- take 90k as an example.

I can deal with plain old haskell lists of this size pretty easily (I figured I'd have to switch to something like [mutable] vectors at some point but it hasn't been a problem yet). But constructing the list items for this list is taking a super long time -- the time seems quadratic. I haven't analyzed the addToList code too thoroughly yet, but I wonder if offering an API that allows adding multiple items at once and then doing the list-widget bookkeeping only once at the end would help. I'll take a deeper look into this when I have a chance but I thought I'd file the bug now in case you have any ideas about where the performance hit is coming from, @jtdaugherty.

**Comment by radix** [comment]
And for what it's worth, once the elements are added to the widget, navigating the list performs reasonably well, so I think this is just a problem of addition taking too long.

**Comment by jtdaugherty** [comment]
Thanks for the pull request. To be honest there are almost certainly some lurking performance hotspots in the library because I deliberately don't worry about performance until it becomes important.  I appreciate the work you've put into this, because it certainly should be easier to do it faster.
