### ISSUE TITLE
`withNormalAttribute` in list item

### ISSUE THREAD

**Issue by listx** [jtdaugherty/vty-ui#70]
In 1.8 (bf5c8b0aa2a5f2e7e41bbf95f42c1e54c1866cfd), if you change line 111 in `demos/ListDemo.hs` from

```
(plainText "a list item") >>=
```

to

```
(plainText "a list item") >>= withNormalAttribute (black on red) >>=
```

the newly-added list items don't change their color. Interestingly, if we change it to

```
(plainText "a list item") >>= withNormalAttribute (withStyle (on black red) bold) >>=

```

the *style* carries over (although colors still have no effect).

Is this a bug?

**Comment by jtdaugherty** [comment]
It sure is. Thank you!

**Comment by listx** [comment]
Thanks for the quick patch!
